spring:
  application:
    name: config-server

  profiles:
    active: ${CONFIG_PROFILE:native}

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATION:classpath:/config}

server:
  port: ${CONFIG_SERVER_PORT:8888}